### ISSUE TITLE
Exc 15: Error running base simulation with updated policy

### ISSUE THREAD

**Issue by ChristianZaeh** [AndreWeiner/ml-cfd-lecture#31] opened 2023-02-19 17:31 UTC
I followed the last steps of the exercise 15 and get the following error when running the `./Allrun` and `./Allrun.pre` files:

`./Allrun.pre
Running blockMesh on /home/christian/drlfoam/examples/base_sim/base
Running setExprBoundaryFields on /home/christian/drlfoam/examples/base_sim/base
Running decomposePar on /home/christian/drlfoam/examples/base_sim/base
Error getting 'numberOfSubdomains' from 'system/decomposeParDict'
Running renumberMesh (1 processes) on /home/christian/drlfoam/examples/base_sim/base 
Error getting 'numberOfSubdomains' from 'system/decomposeParDict'
Running pimpleFoam (1 processes) on /home/christian/drlfoam/examples/base_sim/base 
`
Thank you for the help :)

**Comment by JanisGeise** [comment] 2023-02-19 18:38
Hi @ChristianZaeh,
since the command `numberOfSubdomains` is not found, maybe you forgot to source the *setup-env*. Provided that the `base` directory is still located in `drlfoam/examples/test_training/base` you can try the following steps after making a copy of the original `base` folder:

1. from the top-level of the repository, execute the command `source setup-env`
2. cd into the `drlfoam/examples/test_training/base` folder
3. execute `./Allclean`
4. execute `./Allrun.pre`

You can add the parameter `--container` to the first point as `source setup-env --container` if you don't have a native openfoam installation. In this case you first have to build the singularity container at the top level of the *drlfoam* directory as described in the [drlfoam](https://github.com/OFDataCommittee/drlfoam) repository. Please let me know if this doesn't fix the issue.

Regards,
Janis

**Comment by ChristianZaeh** [comment] 2023-02-19 19:16
Hi @JanisGeise 
ok, I thought the copy has to stay in the drlfoam folder. I moved it now to the exercise folder and setup the environment. I now get:
`./Allrun.pre: line 3: DRL_BASE: parameter null or not set
`
Thank you and kind regards
Christian

**Comment by JanisGeise** [comment] 2023-02-19 20:03
yes, the *base* directory has to stay in the same directory (`drlfoam/examples/test_training/`). The copy is just for backup, in case you want to check out the settings or try out another policy. It is also important that the name of the directory remains *base* and the name of the policy used *policy.pt*.

Regards
Janis

**Comment by ChristianZaeh** [comment] 2023-02-19 20:25
okay I set up the from the top level folder and following the steps I still get:
`./Allrun.pre
Running blockMesh on /home/christian/drlfoam/examples/test_training/base
Running setExprBoundaryFields on /home/christian/drlfoam/examples/test_training/base
Running decomposePar on /home/christian/drlfoam/examples/test_training/base
Error getting 'numberOfSubdomains' from 'system/decomposeParDict'
Running renumberMesh (1 processes) on /home/christian/drlfoam/examples/test_training/base 
Error getting 'numberOfSubdomains' from 'system/decomposeParDict'
Running pimpleFoam (1 processes) on /home/christian/drlfoam/examples/test_training/base 
`
Regards Christian

**Comment by JanisGeise** [comment] 2023-02-20 10:12
ok, can you check out the `log.decomposePar` file if there are any error messages?

Regards,
Janis

**Comment by ChristianZaeh** [comment] 2023-02-20 16:39
yes, there is:
`/home/christian/drlfoam/openfoam/RunFunctions: line 210: decomposePar: command not found`

Regards,
Christian

**Comment by JanisGeise** [comment] 2023-02-20 20:29
@ChristianZaeh , unfortunately I can't reproduce the error. Can you describe what you have done (e.g. what commands did you execute) exactly after the training finished? Further, did you encountered any problems when running the training?

@AndreWeiner, I noticed that I forgot to mention in issue #30 that the parameter `timeStart` in `system/controlDict` need to be set to zero for the coefficients as well as for the probes in order to write out the data during the simulation.

Regards,
Janis

**Comment by AndreWeiner** [comment] 2023-03-08 10:39
Hi @ChristianZaeh,
is this issue resolved from your point of view?
Best, Andre

**Comment by ChristianZaeh** [comment] 2023-03-08 13:10
Hi @AndreWeiner,
Sorry for the late response. I did not get it to work, but  I haven't tried it any further due to exams.
Best,
Christian

**Comment by AndreWeiner** [comment] 2023-03-08 13:21
Alright, thanks for the quick response. Feel free to bring your laptop to the meeting before the exam or to schedule a separate appointment to look at your setup together.
I'll close this issue for now.
Best, Andre

**Closed as completed by AndreWeiner** 2023-03-08 13:21 UTC
Labels: exercise, OpenFOAM
